/* config.h.  Generated automatically by configure.  */
/* $Id: config_h.in,v 3.2 1997/12/10 01:51:44 tom Exp $ */

#define BITS_PER_UNIT 8
#define CHAR_TYPE_SIZE 8
#define HAVE_ATEXIT 1
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_RENAME 1
#define HAVE_STDARG_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRERROR 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_TERMCAP_H 1
#define HAVE_TERM_H 1
#define HAVE_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_VFPRINTF 1
#define HOST_BITS_PER_CHAR 8
#define HOST_BITS_PER_INT 32
#define HOST_BITS_PER_LONG 64
#define HOST_BITS_PER_SHORT 16
#define INT_TYPE_SIZE 32
#define LONG_TYPE_SIZE 64
#define M_TERMINFO 1
#define NEED_TERM_H 1
#define OUTC_RETURN 1
#define RETSIGTYPE void
#define SHORT_TYPE_SIZE 16
#define STDC_HEADERS 1
#define SYSTEM_NAME "darwin25.1.0"
#define TARGET_BELL 007
#define TARGET_BS 010
#define TARGET_CR 015
#define TARGET_FF 014
#define TARGET_NEWLINE 012
#define TARGET_TAB 011
#define TARGET_VT 013
#define TIME_WITH_SYS_TIME 1
